# Generated by Django 3.0.4 on 2022-11-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('password', models.CharField(max_length=128, verbose_name='ユーザーパスワード')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='ユーザーメールアドレス')),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('user_remark', models.CharField(blank=True, max_length=250, verbose_name='ユーザー備考')),
                ('user_type', models.IntegerField(default=1, verbose_name='ユーザータイプ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最終ログイン日付')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理画面アクセスフラグ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField(auto_now_add=True, verbose_name='ログイン日付')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'login_history',
            },
        ),
    ]
